shopping = []
print(shopping)
s=input("ENTER THE STRING B*TCH ")
shopping.append(s)
print(shopping)
s = input("ENTER THE STRING B*TCH ")
shopping.append(s)
print(shopping)
s = input("ENTER THE STRING B*TCH ")
shopping.insert(1,s)
print(shopping)
print(shopping.count("ANUJ"))
s = input("ENTER THE STRING B*TCH ")
shopping.append(s)
s = input("ENTER THE STRING B*TCH ")
shopping.insert(3,s)
print(shopping)
print(len(shopping))
